services:
  - type: web
    name: sofeia-ai-agent
    env: node
    region: frankfurt # EU region for GDPR compliance
    plan: starter # $7/month - upgrade to standard for production
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: cd dist && node index.js
    repo: https://github.com/ottey1969/QuestionMasterSOFEIAAI.git
    branch: main
    rootDirectory: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true # Render will generate a secure random string
      - key: GROQ_API_KEY
        sync: false # Must be set manually
      - key: PERPLEXITY_API_KEY
        sync: false # Must be set manually
      - key: ANTHROPIC_API_KEY
        sync: false # Must be set manually
      - key: PAYPAL_CLIENT_ID
        sync: false # Must be set manually
      - key: PAYPAL_CLIENT_SECRET
        sync: false # Must be set manually
      - key: ADMIN_KEY
        sync: false # Must be set manually
      - key: ADMIN_IP_ADDRESS
        sync: false # Must be set manually
      - key: DATABASE_URL
        fromService: # Reference the database service
          type: pserv
          name: sofeia-ai-db
          property: connectionString

  - type: pserv
    name: sofeia-ai-db
    env: postgres
    region: frankfurt # EU region for GDPR compliance
    plan: starter # $7/month - upgrade to standard for production
    ipAllowList: # Only allow connections from Render
      - 0.0.0.0/0
    disk:
      name: sofeia-ai-db-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
